/*
 * FingerSensor_COnfig.h
 *
 *  Created on: Oct 20, 2022
 *      Author: ali_l
 */

#ifndef HAL_FINGERSENSOR_FINGERSENSOR_CONFIG_H_
#define HAL_FINGERSENSOR_FINGERSENSOR_CONFIG_H_

#define FINGER_SENSOR_1_CHANNEL      ADC_CHANNEL_0
#define FINGER_SENSOR_2_CHANNEL      ADC_CHANNEL_4
#define FINGER_SENSOR_3_CHANNEL      ADC_CHANNEL_5
#define FINGER_SENSOR_4_CHANNEL      ADC_CHANNEL_6
#define FINGER_SENSOR_5_CHANNEL      ADC_CHANNEL_7

#endif /* HAL_FINGERSENSOR_FINGERSENSOR_CONFIG_H_ */
